ALTER TABLE `shops`
    MODIFY COLUMN `data_source` VARCHAR(30) NULL AFTER `id`,
    MODIFY COLUMN `external_store_id` VARCHAR(50) NULL AFTER `data_source`,
    MODIFY COLUMN `name` VARCHAR(100) NOT NULL AFTER `external_store_id`,
    MODIFY COLUMN `phone_number` VARCHAR(20) NULL AFTER `name`,
    MODIFY COLUMN `address` VARCHAR(255) NOT NULL AFTER `phone_number`,
    MODIFY COLUMN `address_detail` VARCHAR(255) NULL AFTER `address`,
    MODIFY COLUMN `province_code` VARCHAR(10) NULL AFTER `address_detail`,
    MODIFY COLUMN `province_name` VARCHAR(50) NULL AFTER `province_code`,
    MODIFY COLUMN `district_code` VARCHAR(10) NULL AFTER `province_name`,
    MODIFY COLUMN `district_name` VARCHAR(50) NULL AFTER `district_code`,
    MODIFY COLUMN `admin_dong_code` VARCHAR(20) NULL AFTER `district_name`,
    MODIFY COLUMN `admin_dong_name` VARCHAR(50) NULL AFTER `admin_dong_code`,
    MODIFY COLUMN `latitude` DECIMAL(10, 7) NOT NULL AFTER `admin_dong_name`,
    MODIFY COLUMN `longitude` DECIMAL(10, 7) NOT NULL AFTER `latitude`,
    MODIFY COLUMN `location_guide` VARCHAR(255) NULL AFTER `longitude`,
    MODIFY COLUMN `parking_info` VARCHAR(255) NULL AFTER `location_guide`,
    MODIFY COLUMN `is_data_active` BOOLEAN NOT NULL DEFAULT true AFTER `parking_info`,
    MODIFY COLUMN `last_synced_at` DATETIME(3) NULL AFTER `is_data_active`,
    MODIFY COLUMN `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) AFTER `last_synced_at`,
    MODIFY COLUMN `updated_at` DATETIME(3) NOT NULL AFTER `created_at`;
